bin/kano-uixinit
The wallpaper settings screen will be launched in the background while
the video plays so it's ready for the user when the playback finishes.
Tested on the Pi and it seems to work fine. The window is waiting there
when the video is over. I didn't notice any stutters/performance hit
of doing this in the video. I guess that's because it's being done on
the GPU.
Related to: https://github.com/KanoComputing/peldins/issues/1865
cc @skarbat @alex5imon
=> kano-uixinit: Speed up the wallpaper screen

bin/kano-uixinit, debian/control
KanoComputing/engage#84
The new Kano World widget should be launched when the desktop is loaded
to provide the full experience.
=> uixinit: Launch Kano World widget at startup

debian/postinst, debian/postrm
* If you open more than one lxterminal, the hourglass stays
active for too long. This changeset fixes this problem
* Resolved by telling lxde to not start the hourglass,
and using kdesk command line tool counterpart instead
cc @alex5imon
=> Fix to remove erratic hourglass on lxterminal

bin/kano-uixinit
@alex5imon This PR calls xrefresh to end the X noobs delay. The splash screen will be in kano-init-flow.
=> Over the NOOBS X delay

bin/kano-uixinit
Starting kano-boards-daemon to handle the LED Speaker API (for now).
The cpu-monitor animation is started after the initflow and checks for
the setting in kano-settings whether it should be started or not.
Also:
* Moved kano-updater to start after vnc to avoid blocking
=> Added kano-boards-daemon to start at bootup

config/systemd/kano.conf, debian/install
This sets the default stop timeout for services to 30s.
So in the worst case, the shutdown will take 30 secs.
cc @Ealdwulf @alex5imon 
Related to: https://github.com/KanoComputing/peldins/issues/2100
=> Adding systemd config to kano dekstop

kdesk/icon-hooks.sh
related to https://github.com/KanoComputing/peldins/issues/2276
=> Fix variable mispelling in icon hook

config/lxpanel/LXDE/panels/panel
The `kano_notifications` plugin was migrated to a stand-alone
application but the LXPanel configuration requiring the plugin remains
meaning that an attempt is made to load it every time LXPanel is
started. Remove this from the configuration to prevent this.
cc @Ealdwulf @pazdera
=> LXPanel Plugins: Remove kano_notifications

bin/kano-uixinit
This PR loads the compositor if the new driver is running, allowing  some acceleration (and right now, breaking kdesk's wallpaper handling). Note that it doesn't seem to be completely necessary for openGL (glxgears works without it). 
@tombettany @skarbat
=> Run xcompmgr at startup if using the new driver.

kdesk/kdesktop/Internet.lnk
This causes kdesk to use the prevailing browser
@ArnaudMoline Please note that the tracking entry will change.
@tombettany @alex5imon
=> Use x-www-browser in kdesk

bin/kano-uixinit, debian/changelog, debian/control
* If running on Kano v3, start in Dashboard mode by default
* An environment variable will instruct it to proceed to normal Desktop mode
@tombettany this simple method would allow us to jump between Dashboard and Desktop mode.
=> Teaching kano-uixinit to run in Dashboard mode

bin/kano-uixinit
This PR removes the call to kano-init-flow from kano-uixinit
There is a unnecessary 1 second delay, but for today we can live with it...
=> Remove the old init flow.

bin/kano-uixinit
* Reduces desktop mode switch by 10 seconds
* syslog would need to be enabled to see the logs (syslog-enable user alias)
* added entries for start and termination steps to clearly compute overall timing
=> Replacing uixinit kano-logs for syslogs

scripts/ldm-session-cleanup-script
Some processes (kano-tracker-ctl, kano-mount-trigger) are being launched multiple times due to
switching between dashboard and computer mode. This adds code to kill any processes left from the previous session.
Longer term, we might want to leave them running/not relaunch to speed up switching
@tombettany @skarbat
=> Kill old processes

config/console/console-setup, debian/install, debian/postinst
This changes the console font to a large size.
Kano-init is then fixed to work with this  here:  https://github.com/KanoComputing/kano-init/pull/28
=> Change console font.

bin/kano-uixinit
This PR changes to run `kano-updater ui bootwindow` before the dashboard so that the updater has an opportunity to finish.
In order to do this, we also move `kano-updater finalise` earlier in the sequence.
@skarbat @tombettany 
@alex5imon Once this is merged we will need to ask GAT without rebooting before updating, to see that it proceeds correctly if it rebooted and expanded the fs.
=> Move call to updater.

bin/make-adventures, debian/changelog, debian/install, kdesk/kdesktop/Adventures.lnk
* A wrapper script linked to the desktop icon
* Gives focus to the app and maximizes if already running
* If a separate Chromium is running, it is killed, then Adventures kicks in
=> Added Make Adventures start script

bin/kano-uixinit
Ensure that the tracking events are synced at boot. Also sync
kano-content and register a startup event.
@skarbat @Ealdwulf I included a couple of extra commands which seemed important in the dashboard init; let me know if they are unneeded.
=> Dashboard Mode: Ensure tracking sync on boot

scripts/ldm-session-cleanup-script
This PR changes the cleanup script to kill a specified list of daemons
@skarbat @tombettany 
For https://github.com/KanoComputing/os-dashboard/issues/108
=> For now, change to kill a blacklist of daemons to avoid killing wifi.

config/systemd/kano.conf, debian/install, debian/postinst
This PR adds  a config option to remove the watchdog error message on reboot.
Unfortunately the version of systemd we are using doesn't support
system.conf.d so we have to edit system.conf in postinst for now. This means our change to the default timeout also weren't working, so I have fixed that as well.
@skarbat @alex5imon 
For https://github.com/KanoComputing/peldins/issues/2345
=> Watchdog fix

bin/kano-dashboard-confirm, bin/kano-uixinit
* In such cases, go directly to Desktop mode
* Having the check on uixinit will work during boot and Greeter login
=> Avoid going to Dashboard on RPi models below 2B

config/openbox/rc.xml
For https://github.com/KanoComputing/kano-overworld/issues/294 @alex5imon 
As discussed, it removed the Iconify button and window-management menus.
=> Remove the Iconize button from all windows.

bin/kano-ui-autostart, bin/kano-uixinit-systemd, scripts/ldm-session-cleanup-script
* The startup tracking event was only happening when going to the Desktop
* Fixed by moving it to Lightdm autostart. It will run after a Greeter login,
on a multiuser kit, and during bootup.
* Removed useless kill commands, which have now migrated to systemd
cc @Ealdwulf
=> Fixed tracking during logon / logout

bin/kano-keyboard-hotkeys, bin/kano-uixinit-systemd, debian/install, systemd/kano-common-keyboard.service, systemd/kano-common.target
This should fix the hotkeys on the Kano Keyboard which were not working after the systemd migration.
Links to ticket: https://github.com/KanoComputing/peldins/issues/2368
cc @tombettany @alex5imon
=> Kano hotkeys in Dashboard and Desktop

config/profile/kano-bashrc
* By default SDL will try to connect to the Xserver which is no supported
* The fix will tell SDL to always attach to the RPi Dispmanx graphics driver
cc @radujipa @tombettany @Ealdwulf
=> Fix potential issue if SDL apps started from ssh or lxterminal

bin/kano-ui-autostart, systemd/kano-desktop-lxpanel.service
* The reason being we were still using the .xsessionrc
* Fixed by moving into the systemd unit file for lxsession
* Removed unnecessary check for Desktop Mode in lightdm autostart
cc @tombettany @Ealdwulf
=> Fixes DESKTOP_MODE environment not set correctly

config/sudoers.d/kano-desktop_conf, config/sudoers.d/kano-environment_conf, debian/install, debian/postinst
* Telling sudo to populate the environment variable
* Moved sudo settings to external files instead of patches during postinst
Replaces: https://github.com/KanoComputing/kano-desktop/pull/174
cc @tombettany
=> Enforcing DESKTOP_MODE to sudoed apps

bin/kano-scratch-launch, debian/install, debian/postinst, kdesk/kdesktop/Scratch.lnk
This PR makes scratch run with sudo @alex5imon
I had also to fix the postinst to manually copy the sudoers file, as dpkg didn't install it for me @tombettany @skarbat. This is a problem I've run into before: if something deletes a file in `/etc`, dpkg assumes that the user has deleted it and won't automatically install a new one as it's a 'config file'. And we delete it in the postrm, which has the same effect. So it must be manually copied.
=> Sudo scratch

config/sudoers.d/kano-desktop_conf, systemd/kano-desktop-lxpanel.service
* Sudoed widgets started from the taskbar cannot be killed by systemd
* Added kill statements for settings and wireless widgets in the systemd unit
* Added restricted sudo aliases to allow these kill commands to proceed blindly
* Confirmed that kano-updater keeps running in the background in such cases
Resolves this issue: https://github.com/KanoComputing/os-dashboard/issues/178
cc @Ealdwulf @radujipa
=> Fixing widgets not killed when going to Dashboard

config/sudoers.d/kano-desktop_conf, systemd/kano-desktop.service
* Scratch is sudoed from kdesk icon, and it does not show on systemd process tree
* Fixing by forcibly killing it on termination of the systemd unit
@Ealdwulf
=> Fixing scratch not closing on Dashboard switch

bin/open-me, bin/use-the-force
Related to https://github.com/KanoComputing/peldins/issues/2382
The issue is due to `kano_init.terminal` sets the overscan [here](https://github.com/KanoComputing/kano-init/blob/jessie/kano_init/terminal.py#L67) automatically... Given that kano-init relies on this to sometimes set it and sometimes not in different stages, I'm going to avoid fixing the issue there. In this PR I've replaced the typewriter with the bash version from `kano-toolset/bin`.
cc @Ealdwulf @tombettany
=> Replaced typewriter to avoid auto overscan from kano-init

bin/kano-dashboard-confirm
KanoComputing/peldins#2377
To reduce friction for returning to the dashboard, remove the dialog
which doesn't actually warn the user about the dangers of changing. The
windows don't have minimize buttons any more so it will cause minimal
problems with people losing what they've done.
cc @skarbat @neue @Roonio
=> Dashboard: Don't ask for confirmation to return

config/sudoers.d/kano-desktop_conf, systemd/kano-desktop-lxpanel.service
This PR prevents the kano-desktop systemd script from killing sentry (and all internet access in parental control mode).
It removes -f argument from pkill. This was too broad - it was catching sentry which only has 'kano-settings' in its arguments. Have tested that it still kills kano-settings.
Points to why   https://github.com/KanoComputing/os-dashboard/issues/202 is a good idea in the long run.
@skarbat @alex5imon
=> Fix sentry

debian/changelog, systemd/kano-common-notifications.service
This changeset depends on: https://github.com/KanoComputing/os-dashboard/pull/212
=> Replacing notifications daemon with new QML based version

systemd/kano-desktop.service
* Hides notifications while screen saver is running
@tombettany
=> Forcing kdesk to run screen saver at a higer graphics layer

systemd/kano-common-notifications.service
* Should the daemon terminate by any reason, systemd should restart it
* Specially important because the notifications pipe would potentially block writers
@Ealdwulf @tombettany
=> Make sure notifications daemon is always alive

bin/use-the-force
Related to https://trello.com/c/eHksitNY/129-use-the-force-does-this
Complements this old fix here .. https://github.com/KanoComputing/kano-desktop/pull/186/files#diff-ba06a1ea91f4be4927f8905d4f5a1068L16
@Ealdwulf @skarbat this alright?
=> Fixed easter egg from setting unintentional overscan

systemd/kano-desktop-lxpanel.service
* systemd was incorrectly terminating the lxpanel and associated widgets
* for lxpanel, he dislikes a kill, so using lxpanelctl tool instead
* graceful termination of optional apps, sudoed through the taskbar widgets
Tested on the PI and seems to resolve the systemd service in RED in all use cases.
@Ealdwulf @tombettany
=> Fixing lxpanel graceful termination through systemd

debian/control
This PR adds the rpi-chromium-mods package which the RPI foundation use to set chromium to use only h264.
This doesn't yet appear to be sufficient to get hardware decoding to work, but it's necessary.
@skarbat @radujipa
=> Add rpi-chromium-mods package.

debian/control, debian/postinst
This PR removes the functionality of setting the chromium master prefs from kano-destop, to a fork of rpi-chromium-mods (which we now depend on)
For https://trello.com/c/QuauOwHJ
There will be another PR to make our changes to rpi-chromium-mods.
=> Don't set chromium master prefs (will be installed by rpi-chromium-mods)

systemd/kano-common-notifications.service
Just noticed that there are a flood of syslogs from the notification daemon, because it's started in verbose mode.
@skarbat
=> Remove verbose flag

debian/control
Add back the chromium backwards-compatability package which provides the symlink.
It isn't being installed because we updated all the app-store packages to use chromium-browser, but as @tombettany points out, we can't remove it because old installs via the app store would stop working on update.
@skarbat
Reopened version of https://github.com/KanoComputing/kano-desktop/pull/209 against `rc`.
@Ealdwulf
=> Add a dependency on chromium

bin/kano-ui-autostart
This changeset populates `xkbcommon` keyboard mapping to all QT5 apps started from Dashboard or Desktop modes.
Tested with spanish keyboard and maps everything correctly except for accents.
=> Make QT5 apps map correct keyboard layouts

bin/kano-ui-autostart
This change fixes terminal quest messages eventually displaying garbage for non-ascii translated messages
=> Fix for some apps not displaying i18n messages correctly

bin/kano-ui-autostart
There was a bug in the condition which regenerated the host keys each time a new user was created, eventually failing and losing the keys and consequently ssh server was down.
Fixed the condition to regenerate host keys only when 1 kano user is found after the init flow, in fact we need just one set of ssh keys per kit.
=> Fix for eventually losing ssh host keys

config/alsa/.asoundrc
The USB microphone I worked with seemed to be recognised as C-Media
CM108. The setup before defined a master channel for controlling
the volume in steps. Here I've defined the capture channel on the
sound card to come by default from a hardware "sound card" with
index 1, which will be the USB mic. There is a chance this will
create problems due to the index when plugging in other audio
devices.
NOTE: I've tested this using Chromium. Previously, with the Settings > Privacy > Content Settings > Microphone > Default, Kano Code wouldn't get any mic input. With this, it now has mic in by default.
@tombettany @skarbat @rluz
=> Support for a USB microphone dongle

bin/kano-ui-autostart
Plays along with this PR: https://github.com/KanoComputing/kano-init/pull/52
=> Allow minimal Xserver start in the background during Overture

systemd/kano-common.target
kano common services is an umbrella to start needed user services.
If any of the dependent services failed to start, the whole unit would go down.
This changeset fixes the issue by establishing them as a soft dependency.
@radujipa @tombettany
=> Make common systemd services recoverable

bin/kano-ui-autostart
This changeset fixes an issue where the Loading dialog remains open if falling back to Desktop Mode, due to Dashboard not supported on current RaspberryPI model.
@tombettany
=> Hide Loading dialog when falling back to Desktop Mode

bin/kano-ui-autostart
The Overture apps needs this service in order to detect and communicate with the hardware.
This also fixes audio going to HDMI
=> Get the boards daemon ready for Overture

debian/kano-desktop.install
The script was missing, which caused the automatic poweroff feature to never work.
Merging right away with your blessing.
=> Add missing script to enable Power Button

debian/control
This package seems to only use a binary from kano-dashboard-common
so changing the dependency to said subpackage. kano-dashboard package
already depends on kano-desktop creating a dependency loop.
Depends on: https://github.com/KanoComputing/os-dashboard/pull/325
=> Fixed circular dependency with kano-dashboard

debian/control, debian/kano-desktop.install
Previously we used to set the alsa config only per user in their
home folders. This causes issues when we want to use the same
config under root.
This is required for `Overture` in the microphone scene, because the app runs with `sudo` privileges.
=> Install alsa config system-wide as well

debian/kano-desktop.install
Completes: https://github.com/KanoComputing/kano-desktop/pull/230/files
=> Added track-ck-type binary which was omitted from the deb install

bin/kano-ui-autostart
The kano-boards-daemon uses desktop notifications to inform users
of low battery signal on CKC. The daemon was only started before
at the end of onboarding by the kano-common.target. We already
bring up the kano-boards.service after the user is created so
this should not affect anything in principle.
=> Start the notifications daemon during onboarding

debian/kano-desktop.install
I missed this bit in https://github.com/KanoComputing/kano-desktop/pull/251
=> Removed enable-power-button binary from the package install script

bin/kano-ui-autostart, debian/changelog
The sound is played when loading the Dashboard, only the first time it boots up.
Tested cases:
* Boot or Reboot from anywhere to go to the Dashboard - sound should play
* Logout from Dashboard and login back in - sound should not play
* Click home button from Classic mode - sound should not play
=> Adding a Dashboard bootup sound

bin/kano-ui-autostart
The welcome sound was not heard due to the boards daemon not being yet loaded.
Fixed by force loading it prior to playing the sound.
Also replaced the sound file, as it was mistakenly using the wrong one.
Manual tests PASSED on:
* RPI with PiHat audio to HDMI
* RPI naked with audio to HDMI
* RPI naked with audio to analog
@tombettany
=> Fixing Dashboard welcome sound

bin/kano-ui-autostart
This changeset removes the Dashboard welcome sound, as it is too early.
Additionally, it exposes the environment variable "COMING_FROM_BOOT" to all systemd services, to indicate a kit bootup. It will be reset when switching users on a multiuser kit.
=> Remove the dashboard welcome sound as it is too early

kdesk/icon-hooks.sh
Prevent tracked session times from overlapping with the screensaver
tracking session by pausing those sessions while the screensaver is
running.
Requires https://github.com/KanoComputing/kano-profile/pull/429
=> Screensaver: Pause tracking during the screensaver

config/lxpanel/LXDE/panels/panel
This is necessary because the volume plugin has never heard of the
system ALSA config - /etc/asound.conf and when it doesn't find one
in the user homedir, it creates one from scratch. This breaks our
volume levels and capture channel for the USB microphone. Removing
it until we find a solution to the problem.
=> Remove the Volume widget in LXPanel in Classic Mode

debian/kano-desktop.install, debian/kano-desktop.preinst
There were a few issues with where asound.conf was being installed
and a mystery over package ownership of /etc/skel/.asoundrc after
it was removed from the debian install script.
=> Fix build issues

config/lxpanel/LXDE/panels/panel, debian/changelog, debian/kano-desktop.install, kdesk-icon/kano-shutdown.desktop
This change complements the translation changes in lxmenu-data
package. It removes the tree apps in the menu (Apps, Files,
Shutdown) to be specified by the menu layout and it adds the
.desktop spec for kano-shutdown.
**NOTE:** This is the application of https://github.com/KanoComputing/kano-desktop/pull/266 to `master`.
=> Added Argentinian Spanish .desktop translation for K > Shutdown

debian/changelog
Spotted this one randomly whilst looking over some files. I believe I introduced this one when applied the backport to the latest master at the time. Package built just fine without this ever since it seems.
=> Fixed a debian changelog typo

bin/kano-ui-autostart, debian/changelog
This moves the `first-boot` event generation out of the Updater
and into the `kano-tracker-ctl generate` and calling the two
binaries asynchronously (with &) to avoid holding up the boot up.
Requires:
https://github.com/KanoComputing/kano-profile/pull/438
https://github.com/KanoComputing/kano-updater/pull/264
Rather than holding up booting to Dashboard by uploading tracking
data to our servers, move content and tracking sync to networks
hooks.
Requires:
https://github.com/KanoComputing/kano-toolset/pull/259
With this change, tracking the `startup` and `kano_screen_kit`
action events are made async. The latter was moved into the
`kano-tracker-ctl generate` given its requirement to check for
the existance of the SK.
Requires:
https://github.com/KanoComputing/kano-profile/pull/439
More …
=> Bootup to Dashboard performance improvements

debian/changelog, kdesk/icon-hooks.sh
This PR adds kano-video-browser to list of processes which inhibit the screensaver.
For https://trello.com/c/hmB9frsm
@brandonjackson I'm assuming we don't want to try and get this into the RC?
=> Screensaver youtube fix

bin/kano-os-loader
Now that splash animations have a timeout, we need to force the bootup animation to stay longer than the 15 seconds default.
This PR plays along with this one: https://github.com/KanoComputing/kano-toolset/pull/269
=> Force a longer timeout to the bootup animation

bin/kano-os-loader, debian/changelog
The low battery signal on boot feature requires the root file system mounted in Read-Only mode.
Since that guarantees no sdcard corruption.
The introduction of the bootup splash animation broke this condition because it failed to remount the file system in this mode, which is what this PR fixes.
Accompanied by this PR to be able to stress test it: https://github.com/KanoComputing/kano-peripherals/pull/59
=> Fix a regression for the Low Battery on boot feature

bin/kano-ui-autostart, debian/changelog
The issue was that the code for disabling the X Screen Saver was
below the point where the script exited quickly when the Overture
onboarding was running. Moving these lines above will ensure that
the X Screen Saver does not start before ours blanking the screen
entirely on the first boot.
=> Fixed X Screen Saver starting on a new user first boot

bin/kano-ui-autostart, debian/changelog
This will call the Updater to continue from an `INSTALLING_UPDATES` state when an update is interrupted. In conjunction with `kano-os-recovery`, this will attempt to restore the system to a clean working state.
=> Re-enabled kano-updater ui boot-window to resume interrupted updates

bin/kano-ui-autostart
After a power failure during an install, the subsequent boot would
launch the Updater but the loading indicator would be over it for
a while until it terminates by itself. This moves the loading
indicator to execute after the Updater.
=> Stop the boot loading indicator if resuming update installation

bin/kano-os-loader, debian/kano-desktop.install
@skarbat found that it's possible by interrupting the updater to be in a situation where
kano-os-loader has been removed from the filesystem but not from `/boot/cmdline.txt`.
Therefore add  a fallback which does nothing.
=> Add fallback script for kano-os-loader in case update gets interrupted.

config/profile/kano-bashrc, debian/changelog
On Stretch, having both libsdl1.2 and libsdl2.0 causes an issue
with this envvar as those executables using v1.2 crash and need
the x11 driver.
Requires:
https://github.com/KanoComputing/kano-overworld/pull/711
=> Removed system wide SDL_VIDEODRIVER=rpi envvar

.gitignore, bin/kano-ui-autostart, debian/changelog, debian/control, features/touch_flipping.feature, systemd/user/kano-common.target
This PR configures touch flipping for user programs launched by dashboard or classic mode.
It doesn't include overture yet.
It depends on https://github.com/KanoComputing/kano-peripherals/pull/63
=> Add touch flipping support.

bin/kano-ui-autostart
This PR moves the flip service to  be run after we inport the environment variables especially DISPLAY etc, otherwise we can't connect to X to detect the touch digitiser device and hence can't configure it on first boot.
=> Fix flipping during overture.

config/openbox/rc.xml, debian/changelog
Bump the titlebar size to allow for easier pressing of the touch
buttons.
=> Openbox: Increase size of titlebar for touch

config/tuxpaint/tuxpaintrc, debian/kano-desktop.install
This PR adds a config file to make tuxpaint full screen.
The alternative would be to change the command line, but it's in a .app file in the tuxpaint package, so this is the best way without forking tuxpaint.
=> Tuxpaint full screen

debian/changelog, systemd/user/kano-desktop.service
Makes sure that the touch home button is availabe only after kdesk, hence Classic mode is ready.
=> Delay touch button startup until kdesk is ready

config/openbox/rc.xml, debian/kano-desktop.postinst, debian/kano-desktop.postrm
This removes any config and installation steps to download and
setup squeak manually for Scratch. `scratch2` now does not
depend on the package anymore, so we don't need it anymore.
Moreover, this currently broke because the `.tar.gz` was moved from the public URL.. **NO!**
=> Remove Squeak dependency madness due to Scratch

debian/changelog, kdesk/icon-hooks.sh
This should also decrease the risk of the screensaver issues we've been seeing.
=> Update list of apps which prevent screensaver

bin/kano-boot-splash, debian/changelog, systemd/system/boot-splash-start.service, systemd/system/boot-splash-terminate.service
Eliminate the need to perform a risky filesystem remount by shifting the
SystemD service to handling the lifetime of the boot animation rather
than having to write something to the filesystem.
Note doesn't definitely solve the boot-up freeze issue (although after many reboots I've not had the problem) but it at least removes one sketchy thing that we do at boot which may cause problems.
=> Boot Splash: Avoid remounting the filesystem

bin/kano-boot-splash, bin/kano-ui-autostart, debian/changelog
Launching it a second time here:
https://github.com/KanoComputing/os-dashboard/blob/master/bin/kano-dashboard-supervisor#L126
=> Remove kano-splash loading anim, handled by dash supervisor

debian/changelog, debian/control
Full documentation in Confluence - [Fixing the Dependency Tree](https://kanocomputing.atlassian.net/wiki/spaces/OS/pages/99254331/Fixing+the+Dependency+Tree)
Used case #2 in https://wiki.debian.org/PackageTransition
Requires: https://github.com/KanoComputing/os-dashboard/pull/386
=> [OS-543] Reverse dependency on kano-desktop, fix dependency loop

bin/kano-refresh-token, debian/changelog, debian/control, debian/kano-desktop.install, systemd/user/kano-common-refresh-token.service, systemd/user/kano-common-refresh-token.timer, systemd/user/kano-common.target
This PR introduces a periodic systemd service to refresh KW login token.
=> [OS-1001] Adding systemd timer to refresh Kano World token

bin/kano-refresh-token, systemd/user/kano-common-refresh-token.service
The token refresh timer script had 2 small problems:
* The Mercury token member was obsoleted by get_token() method
* The command line syntax needs the "refresh" verb, was missing from system trigger
Tested on the RPi, looks to work fine now.
=> Fix refresh token script and system trigger
