KanoComputing/kano-desktop

debian/control, kdesk/kdesktop/Internet.lnk
Wrapping chromium in the session tracker.
Related to: https://github.com/KanoComputing/peldins/issues/1910
cc @skarbat @alex5imon
=> Track chromium

kdesk/kdesktop/Scratch.lnk
cc @alex5imon @skarbat 
Related to: https://github.com/KanoComputing/peldins/issues/1910
=> Track usage of Scratch

debian/control, kdesk/kdesktop/Video.lnk
It is now placed at the last grid position.
cc @rluz @alex5imon
=> New desktop icon for Kano Video Youtube

bin/kano-uixinit, debian/control
Sync in the background at boot.
Related to: https://github.com/KanoComputing/kano-content/issues/20
cc @convolu @alex5imon
=> Content sync

debian/control, kdesk/icon-hooks.sh
https://github.com/KanoComputing/engage/issues/83
=> Added number of users online to World Icon

bin/kano-uixinit, debian/control
This PR adds the call to start the new notifications daemon.
It also adds a dependency on kano-widgets, that will need to be switched later to the new kano-applets package. It depends on https://github.com/KanoComputing/kano-widgets/pull/24
@tombettany @pazdera
=> Run new standalone notifications daemon.

kdesk/icon-hooks.sh
https://github.com/KanoComputing/peldins/issues/2018
@skarbat
=> Fixes offline status

debian/install
Alsamixer hidden config file for Master fader fix
@alex5imon @skarbat
This is for wheezy and jessie!
=> Alsamixer hidden config file for Master fader fix

debian/install
asoundrc fix for jessie and wheezy (LXpanel crash)
=> asoundrc fix for jessie and wheezy (LXpanel crash)

debian/install
asoundrc-fix-wheezy
debian install fix
@skarbat wheezy version
=> asoundrc-fix-wheezy

bin/kano-uixinit
=> default volume fix

bin/kano-uixinit
Moving the first boot volume setting before the init flow
cc @rluz please review
=> Moving the first boot volume config to before the init-flow

bin/kano-uixinit
=> Moving the video playback further up to decrease loading time

scripts/ldm-session-cleanup-script
We need to make sure we receive the event as soon as possible.
cc @alex5imon
=> Upload tracking data on shutdown

kdesk/icon-hooks.sh
=> Upload tracking data when the screen saver starts

scripts/ldm-session-cleanup-script
@pazdera @skarbat could you please review this?
related to https://github.com/KanoComputing/peldins/issues/2121
=> Made kano-sync silent on logout

bin/kano-uixinit
Choose correct number for checking number of partitions.
=> Fix partition count error.

debian/changelog, kdesk/kdesktop/Scratch.lnk, kdesk/kdesktop/Video.lnk
Make Light will be inserted in place 2 instead
work towards https://github.com/KanoComputing/peldins/issues/2162
Needs to be merged on the same day as https://github.com/KanoComputing/make-light/pull/203
=> Move Scratch and Video over by a place

bin/kano-uixinit
Related to: https://github.com/KanoComputing/peldins/issues/2245
cc @alex5imon @convolu @tombettany @skarbat
=> uixinit: Adding a tracking event when internet is up

kdesk/icon-hooks.sh
* Tiny changes to collect the correct variable names
* Avoid sending an IconStatus if there is no fulfilled quests
cc @convolu @radujipa
=> Fixes icon-hooks to parse the profile desktop icon images

bin/kano-uixinit
Related to https://github.com/KanoComputing/peldins/issues/2290
=> Replaced masked alsa-utils with alsa-restore service

bin/kano-uixinit
This PR removes the notification daemon, as this functionality is now provided by the dashboard.
@tombettany @alex5imon
=> Remove Notification daemon

bin/kano-uixinit
* Also, a slight clarification on the new uixinit duties
=> Kano-uixinit does not play the intro video anymore

bin/kano-uixinit, debian/control
For https://github.com/KanoComputing/kano-updater/pull/178
=> This adds a call to a faster version of kano-update ui boot-window.

bin/kano-uixinit
This adds notification daemon back - both in dashboard and desktop modes.
For https://github.com/KanoComputing/peldins/issues/2328
@tombettany @alex5imon
=> Add back notifications

bin/kano-scratch-launch
The use of WRAPPER didn't actually work, just calling sudo directly.
=> Fix sudo command.

config/sudoers.d/kano-desktop_conf
squeak was in sudoers, we need scratch also.
=> Add /usr/bin/scratch to sudoers.

config/openbox/rc.xml
This should fix https://github.com/KanoComputing/peldins/issues/2391 (scratch off the top of the screen)  @alex5imon
=> Fix squeak off-screen issue.

bin/kano-ui-autostart
* Restoring sound the first time we boot into UI
* Simplified first_boot flag as it was mistakenly reset in the script
Addresses: https://github.com/KanoComputing/peldins/issues/2386
cc @Ealdwulf @radujipa
=> Sound volume reboot

systemd/kano-common-notifications.service
@tombettany @Roonio we might want to refine this `wav` file.
The volume seems to be very low compared to the rest of system sounds.
=> Changing sound for new notifications design

bin/kano-uixinit-systemd
In case the cursor was not reset, reset it.
=> Reset cursor

bin/kano-keyboard-hotkeys, config/keyboard/kanokeyboardrc, debian/changelog
Replaces https://github.com/KanoComputing/kano-desktop/pull/212 due to wrong branch.
=> This changeset replaces the K hotkey functionality.

bin/kano-ui-autostart
Harmless, just to avoid searching this info again next time @tombettany @radujipa
=> Added two comments to remember how to debug QT5 international keyboards

bin/kano-screenshot-hotkey, debian/changelog, debian/kano-desktop.install, debian/rules, po/Makefile, po/es_AR.po
It seems to work! @tombettany @radujipa
=> Introduce i18n build and packaging

bin/kano-ui-autostart
Add tracking when the screen kit is detected.
I doubt this API is the right way to query this information though...
Any suggestions @radujipa @Ealdwulf ?
=> Add tracking for the screen kit

bin/track-ck-type, systemd/kano-common.target, systemd/track-ck-type.service
=> Script and systemd unit to track CK Lite and Pro versions

bin/kano-ui-autostart, debian/changelog, debian/control
Related to: https://github.com/KanoComputing/kano-os-home-button/pull/30
=> Adding dashboard loading message dialog

bin/enable-power-button, systemd/enable-power-button.service, systemd/kano-common.target
=> Enabling the power button at bootup after daemons start

bin/track-ck-type
Depends on https://github.com/KanoComputing/kano-peripherals/pull/29
=> Refactored tracking CK type to use detection wrappers for ease

systemd/kano-common.target
Complements this PR: https://github.com/KanoComputing/kano-peripherals/pull/36
=> Fix speaker LEDs daemon not starting

config/alsa/.asoundrc, debian/changelog
Previously we had 7 volume steps with another for silence. This
increases the resolution for better fine tuning the audio volume.
=> Doubled audio volume resolution for better stepping

bin/kano-ui-autostart, debian/changelog
Complements this PR: https://github.com/KanoComputing/os-dashboard/pull/356
=> Replace dashboard loading dialog for splash animation

kdesk/kdesktop/Scratch.lnk
Change to scratch2 on desktop.
=> Update scratch.lnk for scratch2

debian/changelog, debian/control, kdesk/kdesktop/Internet.lnk
Fix User agent string on desktop.
Depends on https://github.com/KanoComputing/kano-apps/pull/119
=> Use new kano-start-browser script contiaing user agent string.

bin/kano-track-space, debian/kano-desktop.install, systemd/user/kano-common-track-space.service, systemd/user/kano-common.target
This PR adds a systemd service which makes a space tracking entry.
=> Add space tracking script, to run at login.

systemd/user/kano-common-track-space.service
=> Remove incorrect BindsTo.

bin/kano-boot-splash, bin/kano-boot-splash-cli, debian/control, debian/kano-desktop.install, features/boot_splash_low_level_cli.feature, features/bootup_animation.feature, systemd/system/boot-splash-start.service
This PR:
* Makes the boot splash switchable
* Adds a cli tool to switch it.
QA: feature files present in this PR show what needs testing.
=> Add boot splash switching functionality.

debian/changelog, debian/control
In order to install this package: https://github.com/KanoComputing/kano-os-homedir-content/pull/1
And replaces this PR: https://github.com/KanoComputing/kano-os/pull/4
=> Adding dependency with Home Directory Content package

bin/kano-ui-autostart, debian/changelog
Note this also removes some tech debt to do with NOOBS.
=> [OS-233] Remove check for <rpi2, it is now handled by kano-init
